CREATE PROC FI_SP_ValCliente
    @CPF VARCHAR(11)
AS
BEGIN
    SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF, ID FROM CLIENTES WITH(NOLOCK) WHERE CPF = @CPF
END;